### ISSUE TITLE
Roadmap 1.0.0-beta

### ISSUE THREAD

**Issue by alajmo** [samiralajmovic/huel#15]
Before deeming Huel feature complete, following features may need to be implemented:

## Focus

* [ ] Refactor - quality of the code isn't the best, a lot of the code is duplicated and there's sections which can be abstracted

* [ ] Harmonize outputs

* [ ] Add tests
* [ ] Add `passed test / tot. tests` at the end

* [ ] Multiple src folders for lint and format
* [ ] Add fail on first error or run all tests before failing (bail flag)

## Features / Usability

* [ ] precommit hook - run `huel lint` after merge to master
* [ ] feature removal - see which features I use and remove those I don't
* [ ] prepublish tag hook - add a pretag git hook which automatically runs the `huel changelog` and adds latest info to github
* [ ] Use in production to see what's missing and needs to be added
* [ ] Support for peer dependencies

* [ ] [Update cli output](https://www.npmjs.com/package/columnify) text
* [ ] Possibly add `npm config set save-prefix` for huel init to only install strict versioning when running `npm install`
* [ ] Custom default dotfiles for each package
* [ ] update-check should check for branches next v2, next etc to see if there's an alpha or beta version
* [ ] Checkout https://github.com/github/git-sizer
* [ ] Checkout https://github.com/nodesecurity/nsp
* [ ] Component generator with dirs (src/components etc)

## Stability & Code Quality

* [ ] Refactor (Read some node.js best practise guide for handling errors)

## Misc

* Investigate https://gist.github.com/gricard/e8057f7de1029f9036a990af95c62ba8
* HTML Validation https://github.com/thedaviddias/Front-End-Checklist
