### ISSUE TITLE
Roadmap 1.0.0-alpha

### ISSUE THREAD

**Issue by samiralajmovic** [samiralajmovic/huel#7]
Things to do before releasing to public:

feat:
* [x] [size-limit](https://github.com/ai/size-limit)
* [ ] [Jarvis, intelligent browser based Webpack dashboard](https://github.com/zouhir/jarvis)
* [x] [depcheck](https://github.com/depcheck/depcheck)
* [x] Optional webpack output name (default **index.js**)
* [x] Add docs for issue-template, pull-request-template
* [x] Automate aliases for webpack
* [x] hal info
* [x] Upgrade webpack 4 (https://medium.com/webpack/webpack-4-code-splitting-chunk-graph-and-the-splitchunks-optimization-be739a861366, https://medium.com/webpack/webpack-4-released-today-6cdb994702d4)
